service: serverless-demo 

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  profile: default

package:
  artifact: bin/release/netcoreapp2.1/hello.zip

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    events:
      - http:
          path: hello
          method: post
  goodbye:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Goodbye
    events:
      - http:
          path: goodbye
          method: get

custom:
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}